import { NadeThrow, NadeThrowDifficulty, NadeThrowTechnique, TickRate } from './NadeThrow';

export const nadeThrows: NadeThrow[] = [
	{
		__type: 'stationary',
		id: 'de_mirage-64-back-alley-to-bench',
		map: 'de_mirage',
		tickRate: TickRate.low,
		difficulty: NadeThrowDifficulty.easy,
		technique: NadeThrowTechnique.JumpThrow,

		from: 'Back alley',
		to: 'Bench',
	},
	{
		__type: 'stationary',
		id: 'de_mirage-64-back-alley-to-bench-2',
		map: 'de_mirage',
		tickRate: TickRate.low,
		difficulty: NadeThrowDifficulty.easy,
		technique: NadeThrowTechnique.JumpThrow,

		from: 'Back alley',
		to: 'Bench',
	},
	{
		__type: 'stationary',
		id: 'de_mirage-64-back-alley-to-connector',
		map: 'de_mirage',
		tickRate: TickRate.any,
		difficulty: NadeThrowDifficulty.easy,
		technique: NadeThrowTechnique.MouseLeft,

		from: 'Back alley',
		to: 'Connector',
	},
	{
		__type: 'stationary',
		id: 'de_mirage-64-back-alley-to-van',
		map: 'de_mirage',
		tickRate: TickRate.low,
		difficulty: NadeThrowDifficulty.easy,
		technique: NadeThrowTechnique.JumpThrow,

		from: 'Back alley',
		to: 'Van',
	},
	{
		__type: 'stationary',
		id: 'de_mirage-64-back-alley-to-short',
		map: 'de_mirage',
		tickRate: TickRate.any,
		difficulty: NadeThrowDifficulty.easy,
		technique: NadeThrowTechnique.MouseLeft,

		from: 'Back alley',
		to: 'Short',
	},
	{
		__type: 'stationary',
		id: 'de_mirage-64-back-alley-to-shops-window',
		map: 'de_mirage',
		tickRate: TickRate.low,
		difficulty: NadeThrowDifficulty.easy,
		technique: NadeThrowTechnique.JumpThrow,

		from: 'Back alley',
		to: 'Shops (window)',
	},
	{
		__type: 'stationary',
		id: 'de_mirage-64-ct-spawn-to-palace',
		map: 'de_mirage',
		tickRate: TickRate.low,
		difficulty: NadeThrowDifficulty.easy,
		technique: NadeThrowTechnique.JumpThrow,

		from: 'CT spawn',
		to: 'Palace',
	},
	{
		__type: 'stationary',
		id: 'de_mirage-64-ct-spawn-to-ramp',
		map: 'de_mirage',
		tickRate: TickRate.low,
		difficulty: NadeThrowDifficulty.easy,
		technique: NadeThrowTechnique.JumpThrow,

		from: 'CT spawn',
		to: 'Ramp',
	},
	{
		__type: 'stationary',
		id: 'de_mirage-64-t-roof-to-a-site',
		map: 'de_mirage',
		tickRate: TickRate.any,
		difficulty: NadeThrowDifficulty.medium,
		technique: NadeThrowTechnique.MouseLeft,

		from: 'T roof',
		to: 'A (site)',
	},
	{
		__type: 'moving',
		id: 'de_mirage-64-t-spawn-to-a-site',
		map: 'de_mirage',
		tickRate: TickRate.any,
		difficulty: NadeThrowDifficulty.medium,
		technique: NadeThrowTechnique.JumpThrow,

		from: 'T spawn',
		to: 'A (site)',
	},
	{
		__type: 'moving',
		id: 'de_mirage-64-t-spawn-to-bench',
		map: 'de_mirage',
		tickRate: TickRate.low,
		difficulty: NadeThrowDifficulty.medium,
		technique: NadeThrowTechnique.JumpThrow,

		from: 'T spawn',
		to: 'Bench',
	},
	{
		__type: 'stationary',
		id: 'de_mirage-64-t-spawn-to-connector',
		map: 'de_mirage',
		tickRate: TickRate.low,
		difficulty: NadeThrowDifficulty.medium,
		technique: NadeThrowTechnique.JumpThrow,

		from: 'T spawn',
		to: 'Connector',
	},
	{
		__type: 'stationary',
		id: 'de_mirage-64-t-spawn-to-ct',
		map: 'de_mirage',
		tickRate: TickRate.low,
		difficulty: NadeThrowDifficulty.easy,
		technique: NadeThrowTechnique.JumpThrow,

		from: 'T spawn',
		to: 'CT spawn',
	},
	{
		__type: 'stationary',
		id: 'de_mirage-64-t-spawn-to-jungle',
		map: 'de_mirage',
		tickRate: TickRate.low,
		difficulty: NadeThrowDifficulty.medium,
		technique: NadeThrowTechnique.JumpThrow,

		from: 'T spawn',
		to: 'Jungle',
	},
	{
		__type: 'moving',
		id: 'de_mirage-64-t-spawn-to-shops-door',
		map: 'de_mirage',
		tickRate: TickRate.low,
		difficulty: NadeThrowDifficulty.medium,
		technique: NadeThrowTechnique.JumpThrow,

		from: 'T spawn',
		to: 'Shops (door)',
	},
	{
		__type: 'moving',
		id: 'de_mirage-64-t-spawn-to-shops-window',
		map: 'de_mirage',
		tickRate: TickRate.low,
		difficulty: NadeThrowDifficulty.hard,
		technique: NadeThrowTechnique.JumpThrow,

		from: 'T spawn',
		to: 'Shops (window)',
	},
	{
		__type: 'stationary',
		id: 'de_mirage-64-t-spawn-to-short',
		map: 'de_mirage',
		tickRate: TickRate.low,
		difficulty: NadeThrowDifficulty.medium,
		technique: NadeThrowTechnique.JumpThrow,

		from: 'T spawn',
		to: 'Short',
	},
	{
		__type: 'moving',
		id: 'de_mirage-64-t-spawn-to-window',
		map: 'de_mirage',
		tickRate: TickRate.low,
		difficulty: NadeThrowDifficulty.medium,
		technique: NadeThrowTechnique.JumpThrow,

		from: 'T spawn',
		to: 'Window',
	},
	{
		__type: 'stationary',
		id: 'de_mirage-64-top-mid-to-b-site',
		map: 'de_mirage',
		tickRate: TickRate.low,
		difficulty: NadeThrowDifficulty.medium,
		technique: NadeThrowTechnique.JumpThrow,

		from: 'Top mid',
		to: 'B (site)',
	},
	{
		__type: 'stationary',
		id: 'de_mirage-64-top-mid-to-firebox',
		map: 'de_mirage',
		tickRate: TickRate.low,
		difficulty: NadeThrowDifficulty.medium,
		technique: NadeThrowTechnique.JumpThrow,

		from: 'Top mid',
		to: 'A (firebox)',
	},
	{
		__type: 'stationary',
		id: 'de_mirage-64-top-mid-to-short',
		map: 'de_mirage',
		tickRate: TickRate.low,
		difficulty: NadeThrowDifficulty.easy,
		technique: NadeThrowTechnique.JumpThrow,

		from: 'Top mid',
		to: 'Short',
	},
];
